import os
import json
import time
from duckduckgo_search import DDGS

# --- 1. DEFINE TOOLS ---

def web_search_tool(query: str) -> str:
    """Searches the web using DuckDuckGo and returns top results."""
    print(f"\n[TOOL CALL] Executing Web Search for: '{query}'")
    try:
        results = DDGS().text(query, max_results=3)
        if not results:
            return "Error: No results found for the query."
        
        formatted_results = "\n".join([f"- Title: {r['title']}\n  URL: {r['href']}\n  Snippet: {r['body']}" for r in results])
        return formatted_results
    except Exception as e:
        return f"Tool Error: Failed to execute search due to {str(e)}"

def save_report_tool(content: str, filename: str = "agent_report.md") -> str:
    """Saves the final synthesized report to a markdown file."""
    print(f"\n[TOOL CALL] Saving report to {filename}")
    try:
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)
        return f"Success: Report saved locally to {filename}"
    except Exception as e:
        return f"Tool Error: Could not save file due to {str(e)}"


# --- 2. THE AGENT ORCHESTRATOR & PLANNER ---

class AgenticSystem:
    def __init__(self, goal: str):
        self.goal = goal
        self.plan = []
        self.memory = []

    def generate_plan(self):
        """Autonomously decomposes the high-level goal into sequential steps."""
        print(f"\n--- [1] PLANNING PHASE ---")
        print(f"Goal received: '{self.goal}'")
        
        self.plan = [
            {"step": 1, "task": f"Perform live web search to gather data for: {self.goal}", "tool": "search"},
            {"step": 2, "task": "Synthesize and structure the gathered web findings into a report format", "tool": "synthesize"},
            {"step": 3, "task": "Save the final structured report to disk", "tool": "save"}
        ]
        
        print("Generated Plan Successfully:")
        for p in self.plan:
            print(f"  Step {p['step']}: {p['task']} (Tool: {p['tool']})")

    def execute_step_with_recovery(self, step):
        """Executes a step and handles failures/self-correction gracefully."""
        tool_type = step['tool']
        print(f"\n--- [2] EXECUTING STEP {step['step']}: {step['task']} ---")
        
        if tool_type == "search":
            query = self.goal
            data = web_search_tool(query)
            
            # --- SIMULATED ERROR & SELF-CORRECTION HANDLING ---
            if "Error" in data or len(data.strip()) < 50:
                print("[WARNING] Search tool returned weak results or failed. Initiating Self-Correction...")
                fallback_query = "industry tech overview recent trends"
                print(f"[RECOVERY] Retrying search with simplified fallback query: '{fallback_query}'")
                data = web_search_tool(fallback_query)
            
            self.memory.append(data)
            return data

        elif tool_type == "synthesize":
            print("[TOOL CALL] Synthesizing data into structured Markdown report (Local Engine)...")
            context_data = "\n".join(self.memory)
            
            report_content = f"""# Autonomous Agent Research Report

## Objective / Goal
{self.goal}

## Executive Summary
This report was autonomously generated by the Agentic AI system by sourcing live information from the web, executing multi-step reasoning, and formatting the findings.

---

## Key Findings & Sourced Data
{context_data}

---

## Conclusion & Next Steps
The agent successfully processed the goal, utilized live search tools, handled tool feedback loops, and structured the final output into this Markdown document.
"""
            self.memory.append(report_content)
            return report_content

        elif tool_type == "save":
            report_content = self.memory[-1] if self.memory else "No content generated."
            result = save_report_tool(report_content)
            return result

    def run(self):
        self.generate_plan()
        for step in self.plan:
            result = self.execute_step_with_recovery(step)
            print(f"[STATUS] Step {step['step']} completed.")
            time.sleep(1)
        print("\n--- [3] AGENT EXECUTION FINISHED SUCCESSFULLY ---")


# --- 3. MAIN SCRIPT ENTRYPOINT ---
if __name__ == "__main__":
    import sys
    user_goal = "Research and summarize the top developments in Agentic AI."
    if len(sys.argv) > 1:
        user_goal = " ".join(sys.argv[1:])
        
    agent = AgenticSystem(goal=user_goal)
    agent.run()